port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
geodata-mode: true
geox-url:
  geoip: https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip.dat
  mmdb: https://raw.githubusercontent.com/Loyalsoldier/geoip/release/GeoLite2-Country.mmdb
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback:
  - https://dns.cloudflare.com/dns-query
  - tls://8.8.4.4:853
  fallback-filter:
    geoip: true
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
proxies:
- name: 🇭🇰 香港01-1E
  server: gy.666666222.shop
  port: 34338
  type: ss
  cipher: chacha20-ietf-poly1305
  password: 061838c9-14b3-437c-ba75-877e46c628b2
  udp: true
proxy-groups:
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - 故障转移
  - DIRECT
  - 手动选择
- name: 自动选择
  type: url-test
  proxies:
  - 🇭🇰 香港01-1E
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 故障转移
  type: fallback
  proxies:
  - 🇭🇰 香港01-1E
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 手动选择
  type: select
  proxies:
  - 🇭🇰 香港01-1E

rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
- IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
- IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
- IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
- IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
- IP-CIDR6,::1/128,DIRECT,no-resolve
- IP-CIDR6,fc00::/7,DIRECT,no-resolve
- IP-CIDR6,fe80::/10,DIRECT,no-resolve
- IP-CIDR6,fd00::/8,DIRECT,no-resolve
- GEOIP,CN,DIRECT
- MATCH,节点选择
